### ISSUE TITLE
pandas_schema.__version__ does not return package version

### ISSUE THREAD

**Issue by chfischer** [TMiguelT/PandasSchema#11]
The package does not return version information.

**Comment by smarie** [comment]
For what's worth, a good way to do this automatically is by using the great `setuptools_scm` library, like this: https://smarie.github.io/python-getversion/#package-versioning-best-practices

**Comment by TMiguelT** [comment]
Is it not possible to just use setuptools to interrogate the version?
```
>>> from pkg_resources import get_distribution
>>> dist = get_distribution('pandas_schema')
>>> dist.version
'0.3.1'
```

This seems easy enough, no?

**Comment by smarie** [comment]
Two completely independent topics:

- this issue seems to be about how to easily create the `__version__` attribute in your project so as to comply with PEP396. To do so in an easy and fully automatic way, I recommend the procedure mentioned above, that relies on `setuptools_scm`. I personally use it on several packages. This is how I do it : https://github.com/smarie/python-makefun/issues/45

 - another issue that you mention in your last comment, (that is off-topic for this project) is how can users reliably get the version of *any* package. Just for reference, `setuptools` (that you mention) has many limitations, it can not get the version of all packages. That's why I created `getversion`, a package that combines setuptools with PEP396 and several other methods, so that you are almost guaranteed to get a version number, whatever twisted package you're asking the version for :)
