### ISSUE TITLE
Distinct across multiple columns

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [TMiguelT/PandasSchema#38]
I am not sure if this is supported currently, or how to implement it as custom validator. 

I want distinct values across two columns, so that this is okay:

```
sample    value
1         2
2         2
```

But this is not:

```
sample    value
1         2
1         2
```

**Comment by TMiguelT** [comment]
Unfortunately not, the design of `pandas_schema` 0.X.X is such that every validation is on a per-column basis. This will be fixed in 1.X.X (and indeed I have a demonstration of this behaviour here: https://github.com/TMiguelT/PandasSchema/pull/33/files#diff-966a41d8c6ecfc10e1c7137d86a9bc18R50-R61), but who knows when that will be, because it's been hard to find the time to finish it.

**Comment by Maarten-vd-Sande** [comment]
Ok, then I already have a feature request for it to work on a subset of columns :innocent: . Seems like the current implementation does not support this right?

If you want (and if I have time, not too soon), I could start a PR for this

**Comment by TMiguelT** [comment]
The current (and future) releases support this: https://tmiguelt.github.io/PandasSchema/#pandas_schema.schema.Schema.validate

**Comment by Maarten-vd-Sande** [comment]
Ah I see. Just to be sure I understand: I then would use `DistinctRowValidation` and use validate on a list of columns? 

Feel free to close the issue (either now or with the new release). Thanks for all your help :+1:

**Comment by TMiguelT** [comment]
Right, so you want unique rows but across a subset of the columns. I don't think you can currently do that in the future release but I'll look into it.

**Comment by TMiguelT** [comment]
I'll keep the issue open since it's still not solved in a release.

**Comment by TMiguelT** [comment]
Closing in favour of the more general #57 that I just opened.
