### ISSUE TITLE
Allow a flag like ignoreCase for InListValidation

### ISSUE THREAD

**Issue by Abhisek1994Roy** [TMiguelT/PandasSchema#46]
Suppose I want to do a InListValidation and I have these two keys- ["paid", "unpaid"].
It would be great if we could ignore the case using a flag. 
Current options include- 
1. Adding every possible combination like- ["Paid", "PAID",.....] - not feasible
2. Doing a Regex Match
3. Adding custom function.

**Comment by TMiguelT** [comment]
I agree, this is a reasonable request. Unfortunately the underlying pandas function: [`Series.isin`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.isin.html) doesn't support this. I suppose because it needs to work regardless of whether it's dealing with text or not.

That said, I could add a case insensitive flag that converts it to lowercase, converts the provided list to lowercase also, and then calls `isin`. It would break if used on non-text data however.

**Comment by Abhisek1994Roy** [comment]
Right @TMiguelT . It can be an optional flag, which would only work for a list of strings. Let me take a stab at it and give you a pull request.

**Comment by Abhisek1994Roy** [comment]
@TMiguelT I cloned the code and realized that this flag is already there, and it works. 
`Column('InterestType', [InListValidation(['flat', 'reducing'], case_sensitive=False)]),`
There is a case_sensitive flag, but I guess it needs to be added to the documentation.

**Comment by TMiguelT** [comment]
Huh, there you go. Well this should be sorted once I get the documentation building automatically

**Comment by Abhisek1994Roy** [comment]
Yep. Closing this.
